#!/usr/bin/env python3
# targets.py - 100 Target OTP WhatsApp
# SCRIPETEREN OTP - scripeterenotp

import uuid
import random
from utils import fmt_08, fmt_nocode, fmt_plus, fmt_phone_only

TARGETS = [
    # ===== SESI 1 (1–50) =====
    {'name': 'HRS-BRE', 'post_type': 'hrsbre', 'number_fmt': fmt_08, 'success_on': ['success', 'berhasil', 'otp']},
    {'name': 'EraFone', 'post_type': 'erafone', 'number_fmt': lambda p: p, 'success_on': ['Success Request OTP']},
    {'name': 'PlanetBan', 'post_type': 'planetban', 'number_fmt': fmt_08, 'success_on': ['status":true']},
    {'name': 'TuneUp', 'post_type': 'tuneup', 'number_fmt': fmt_08, 'success_on': ['"success":true']},
    {'name': 'HashMicro', 'post_type': 'hashmicro', 'number_fmt': fmt_phone_only, 'success_on': ['success', 'thank']},
    {'name': 'Klook', 'post_type': 'klook', 'number_fmt': fmt_plus, 'success_on': ['requestId']},
    {'name': 'Internet Rakyat', 'post_type': 'internetrakyat', 'number_fmt': fmt_08, 'success_on': ['"statusCode":200']},
    {'name': 'Ultramilk', 'post_type': 'ultramilk', 'number_fmt': lambda p: p, 'success_on': ['success']},
    {'name': 'Kaniva', 'post_type': 'kaniva', 'number_fmt': fmt_08, 'success_on': ['"message":"success"']},
    {'name': 'Jembatani', 'post_type': 'jembatani', 'number_fmt': fmt_08, 'success_on': ['"success":true']},
    {'name': 'RCX', 'post_type': 'rcx', 'number_fmt': fmt_08, 'success_on': ['challenge', 'redirecting']},
    {'name': 'Sahabat Teknisi', 'post_type': 'sahabatteknisi', 'number_fmt': fmt_08, 'success_on': ['success']},
    {'name': 'Auto2000', 'post_type': 'auto2000', 'number_fmt': fmt_08, 'success_on': ['"acknowledge":1']},
    {'name': 'Astra Daihatsu', 'post_type': 'astra_daihatsu', 'number_fmt': fmt_plus, 'success_on': ['OTP Success']},
    {'name': 'Royal Canin', 'post_type': 'royal_canin', 'number_fmt': fmt_plus, 'success_on': ['SUCCESS']},
    {'name': 'Watsons', 'post_type': 'watsons', 'number_fmt': fmt_phone_only, 'success_on': ['token']},
    {'name': '99.co', 'post_type': '99co', 'number_fmt': fmt_plus, 'success_on': ['ok']},
    {'name': 'Belirumah.co', 'post_type': 'belirumahco', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Fastwork', 'post_type': 'fastworkid', 'number_fmt': fmt_08, 'success_on': ['reference_code']},
    {'name': 'Beautyhaul', 'post_type': 'beautyhaul', 'number_fmt': fmt_phone_only, 'success_on': []},
    {'name': 'Hainaya', 'post_type': 'hainaya', 'number_fmt': fmt_phone_only, 'success_on': ['otp', 'success']},
    {'name': 'MinumYukKaka', 'post_type': 'minumyukkaka', 'number_fmt': fmt_08, 'success_on': ['IsSuccess']},
    {'name': 'SIDEMANG', 'post_type': 'sidemang', 'number_fmt': fmt_08, 'success_on': ['otpDispatched']},
    {'name': 'LaporMasBup', 'post_type': 'lapormasbup', 'number_fmt': fmt_08, 'success_on': ['berhasil', 'warga_id']},
    {'name': 'PTSP Kemenag', 'post_type': 'ptspkemenag', 'number_fmt': fmt_08, 'success_on': ['success', 'user']},
    # JSON Handlers (26–33)
    {'name': 'Pinhome', 'post_type': 'pinhome', 'number_fmt': fmt_nocode, 'success_on': ['secretcode']},
    {'name': 'Maulagi', 'post_type': 'maulagi', 'number_fmt': fmt_08, 'success_on': ['"status":"success"']},
    {'name': 'Rumah123', 'post_type': 'rumah123', 'number_fmt': lambda p: p, 'success_on': ['requestid']},
    {'name': 'Paper', 'post_type': 'paper', 'number_fmt': lambda p: p, 'success_on': ['otp']},
    {'name': 'Dunia Games', 'post_type': 'duniagames', 'number_fmt': fmt_plus, 'success_on': ['otp']},
    {'name': 'Bunda Hospital', 'post_type': 'bunda', 'number_fmt': lambda p: int(p), 'success_on': ['otp']},
    {'name': 'Bonus Belanja', 'post_type': 'bonusbelanja', 'number_fmt': lambda p: p, 'success_on': ['error":false']},
    {'name': 'Matahari', 'post_type': 'matahari', 'number_fmt': fmt_08, 'success_on': ['otp','success','code']},
    # E-commerce & Fintech (34–50)
    {'name': 'Tokopedia', 'post_type': 'tokopedia', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Shopee', 'post_type': 'shopee', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Bukalapak', 'post_type': 'bukalapak', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Grab', 'post_type': 'grab', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Gojek', 'post_type': 'gojek', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'OVO', 'post_type': 'ovo', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'DANA', 'post_type': 'dana', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'LinkAja', 'post_type': 'linkaja', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'BCA', 'post_type': 'bca', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Mandiri', 'post_type': 'mandiri', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'BNI', 'post_type': 'bni', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'BRI', 'post_type': 'bri', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Traveloka', 'post_type': 'traveloka', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Agoda', 'post_type': 'agoda', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Tiket.com', 'post_type': 'tiketcom', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Pegipegi', 'post_type': 'pegipegi', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'RedDoorz', 'post_type': 'reddoorz', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},

    # ===== SESI 2 (51–100) =====
    {'name': 'Blibli', 'post_type': 'blibli', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'JD.ID', 'post_type': 'jdid', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Lazada', 'post_type': 'lazada', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Zalora', 'post_type': 'zalora', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Sociolla', 'post_type': 'sociolla', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Oriflame', 'post_type': 'oriflame', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Herbalife', 'post_type': 'herbalife', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Fore Coffee', 'post_type': 'forecoffee', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Kopi Kenangan', 'post_type': 'kopikenangan', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Starbucks', 'post_type': 'starbucks', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': "McDonald's", 'post_type': 'mcd', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'KFC', 'post_type': 'kfc', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Burger King', 'post_type': 'burgerking', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Pizza Hut', 'post_type': 'pizzahut', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': "Domino's", 'post_type': 'dominos', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'GoFood', 'post_type': 'gofood', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'GrabFood', 'post_type': 'grabfood', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'ShopeeFood', 'post_type': 'shopeefood', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Maxim', 'post_type': 'maxim', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'inDrive', 'post_type': 'indrive', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'MyTelkomsel', 'post_type': 'mytelkomsel', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Indosat', 'post_type': 'indosat', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'XL Axiata', 'post_type': 'xl', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Tri', 'post_type': 'tri', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Smartfren', 'post_type': 'smartfren', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'PLN Mobile', 'post_type': 'pln', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'BPJS', 'post_type': 'bpjs', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'DJP Online', 'post_type': 'djp', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'eHAC', 'post_type': 'ehac', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'PeduliLindungi', 'post_type': 'pedulilindungi', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'MyPertamina', 'post_type': 'mypertamina', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Bukalapak Partner', 'post_type': 'bukalapakpartner', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'SiCepat', 'post_type': 'sicepat', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'J&T Express', 'post_type': 'jnt', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Ninja Xpress', 'post_type': 'ninjaxpress', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Anteraja', 'post_type': 'anteraja', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'POS Indonesia', 'post_type': 'posindonesia', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Lion Air', 'post_type': 'lionair', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Garuda Indonesia', 'post_type': 'garuda', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Citilink', 'post_type': 'citilink', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Batik Air', 'post_type': 'batikair', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Sriwijaya Air', 'post_type': 'sriwijayaair', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'AirAsia', 'post_type': 'airasia', 'number_fmt': fmt_plus, 'success_on': ['success', 'otp']},
    {'name': 'Super Indo', 'post_type': 'superindo', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Hypermart', 'post_type': 'hypermart', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Transmart', 'post_type': 'transmart', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Alfamart', 'post_type': 'alfamart', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Indomaret', 'post_type': 'indomaret', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'MyBCA', 'post_type': 'mybca', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
    {'name': 'Jenius', 'post_type': 'jenius', 'number_fmt': fmt_08, 'success_on': ['success', 'otp']},
]